### ISSUE TITLE
vertaisarviointi 1

### ISSUE THREAD

**Issue by tapsamies** [sumrika/cryptofolio#1]
Sovellusidea on mielenkiintoinen ja opit varmasti paljon sen toteuttaessasi. Kurssin idean mukaisesti csv -muotoiset datalähteet tulisi muuttaa postgresiin, luonnollisesti en tunne optimaalisinta toteutustapaa tuolle, mutta tekisin itse niin, että sovellus katsoo käynnistyessään, onko tietokannan taulut tyhjiä vai ei. Jos tyhjät:

- read_csv.py -tiedostossa määriteltäisiin käytetty tietokanta muuttujalle db, koodilla
```python
app.config["SQLALCHEMY_DATABASE_URI"] = getenv("DATABASE_URL").replace("://", "ql://", 1)

db = SQLAlchemy(app)
```
ja for loopin sisälle muutetaan linelist -tauluun lisäävä koodi muotoon:

```python
sql = "INSERT INTO cryptos (name, price, marketcap, date) VALUES (:name, :price, :marketcap, NOW())"
db.session.execute(sql, {"name":part[1], "price":part[3], "marketcap":part[9]})
db.session.commit()
```
jos taulut ovat jo olemassa, niin tekisin siten, että katsoisin niiden timestampin ja jos aikaa on kulunut jo riittävästi, niin lisäisin taulukkoon (verkko?) datalähteestä uuden rivin assetille. Kun tietoja halutaan jossain vaiheessa käyttää, niin järjestäisin assetit timestamppien mukaan ja näyttäisin viimeisimmän ensin. Jos haluat rakentaa graafin assettien hintakehityksestä, niin silloin ottaisin assettikohtaisen selectin ja rakentaisin timestamppien mukaan järjestetystä listasta graafin käyttäjän nähtäväksi.

Treidien toteuttaminen nykyisellä skeemalla antaa karkean kuvan, laittaisin itse 'holdings' tauluun lisäksi kulut niin saa tarkkuutt ja 'trades' -tauluun muuttaisin 'price' -muuttujan, 'entryprice' ja 'exitprice' -muuttujiksi ja jos taulussa 'holdings' on kulut mukana, niin saat suht simppelisti laitettua myös treidin kokonaisvoiton yhdeksi sarakkeeksi 'trades' -tauluun. Hintadatan hakisin esim bitfinexistä koska pidän heidän apia suht simppelinä ja julkisesta lähteestä saat tarvittavan informaation: [linkki](https://docs.bitfinex.com/reference/rest-public-ticker)

Tuli myös bitfinexin apia katsoessa ettet periaatteessa tarvitse csv -tiedostoja ollenkaan, vaan voit ottaa myös historiallisia kynttilöitä minuutin tarkkuudella suht reilun määrän ja tallentaa ne sitten omaan tietokantaasi. Jos käytät vain yhtä taulua asseteille, niin taululla voi potentiaalisesti tulla äärimmäisen paljon kokoa nopeasti ja yksi mahdollinen vaihtoehto olisi tehdä jokaiselle assetille oma taulu. Taulut voisi luoda esim siinä vaiheessa kun katsot csv -tiedostosta assettien nimet ja luot jollain "CREATE TABLE nönnönöö" komennolla assettia vastaavat taulut tietokantaasi.

Treidaaminen on itselleni tuttua perinteisten assettien puolella ja tiedän että projektissasi tulee olemaan helposti suht paljon duunia, niin kannattaa varata hyvin aikaa tekemiselle ja käyttää apuja mahdollissimman paljon.

**Comment by sumrika** [comment]
Kiitokset todella paljon hyvästä vertaisarvioinnistasi. Arviointi on tehty todella miettien ja hyviä ehdotuksia esittäen. 

Joo, olen nyt huomannut, että sovelluksen toteuttamisessa on minulle haasteita. ja paljon pitää opetella uusia asioita.  Pidän asioiden oppimista tärkeimpänä tässä harjoitustyössä. Taitoni eivät vielä riitä siihen, millaisen sovelluksen haluaisin. Nöyrästi eteenpäin.

**Comment by sumrika** [comment]
En murehdi , vähän toki stressasin aluksi. Aion saada aikaan sellaisen sovelluksen, mihin taitoni tällä hetkellä riittävät. 
Sinulla on erittäin hyviä vinkkejä. Kiitokset taas. 

Terkuin,
Kari

**Comment by sumrika** [comment]
Erittäin paljon kiitoksia.

Jatkan sovellukseni parissa. Todo: CSV tietokantaan. API kokeiluja. Kirjautumissivu. 

Hyvää viikon jatkoa.
